# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: sandeepdhankhar/Dual-Encryption
          event-type: java-build
          client-payload: '{"repository": "${{ github.repository }}", "sha": "${{ github.sha }}"}'


#container: gradle:jdk8

#    steps:
#    - uses: actions/checkout@v3
#    - name: Build code
#      run:  ./gradlew build
#      shell: bash
